# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1c3408745b978cc2ab7918adf43c039"
name = "faqs"
handle = "faqs-14"
application_url = "https://scholar-fork-cocktail-dating.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lalalipsbd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://scholar-fork-cocktail-dating.trycloudflare.com/auth/callback",
  "https://scholar-fork-cocktail-dating.trycloudflare.com/auth/shopify/callback",
  "https://scholar-fork-cocktail-dating.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
